// ─── Seed-Based Realistic Bounds for Editor Sliders ──────────────────────────
const SEED_BOUNDS = {
  1:  {efficiency:{min:0,max:100,lo:85,hi:97,desc:"Top-5 KenPom territory"},    form:{min:1,max:10,lo:7,hi:10,desc:"1-seeds rarely limp in"},    coaching:{min:1,max:10,lo:7,hi:10,desc:"Elite coaches at this seed"},   regDiff:{min:1,max:10,lo:5,hi:9,desc:"Earned their 1-line"}},
  2:  {efficiency:{min:0,max:100,lo:77,hi:93,desc:"KenPom top 15"},             form:{min:1,max:10,lo:6,hi:10,desc:"Strong late-season run"},       coaching:{min:1,max:10,lo:6,hi:10,desc:"Usually veteran staff"},       regDiff:{min:1,max:10,lo:5,hi:9,desc:"Proved it all season"}},
  3:  {efficiency:{min:0,max:100,lo:70,hi:88,desc:"Top-25 KenPom range"},       form:{min:1,max:10,lo:6,hi:9,desc:"Consistent performers"},         coaching:{min:1,max:10,lo:5,hi:9,desc:"Experienced coaching"},         regDiff:{min:1,max:10,lo:4,hi:8,desc:"Proved it all season"}},
  4:  {efficiency:{min:0,max:100,lo:65,hi:83,desc:"KenPom 20–40"},              form:{min:1,max:10,lo:5,hi:9,desc:"Good but inconsistent"},          coaching:{min:1,max:10,lo:5,hi:9,desc:"Experienced coaching"},         regDiff:{min:1,max:10,lo:4,hi:8,desc:"Conference champ range"}},
  5:  {efficiency:{min:0,max:100,lo:60,hi:80,desc:"KenPom 25–50 typical"},      form:{min:1,max:10,lo:5,hi:9,desc:"Dangerous mid-major zone"},       coaching:{min:1,max:10,lo:5,hi:9,desc:"Solid coaching at this line"},  regDiff:{min:1,max:10,lo:4,hi:8,desc:"Mid-major champs here"}},
  6:  {efficiency:{min:0,max:100,lo:56,hi:76,desc:"KenPom 30–60 range"},        form:{min:1,max:10,lo:5,hi:8,desc:"Steady but beatable"},             coaching:{min:1,max:10,lo:4,hi:9,desc:"Wide coaching variance"},       regDiff:{min:1,max:10,lo:3,hi:7,desc:"Conference bracket winner"}},
  7:  {efficiency:{min:0,max:100,lo:52,hi:73,desc:"KenPom 35–65 typical"},      form:{min:1,max:10,lo:5,hi:8,desc:"Inconsistent down stretch"},       coaching:{min:1,max:10,lo:4,hi:8,desc:"Wide coaching variance"},       regDiff:{min:1,max:10,lo:3,hi:7,desc:"Earned a bid but barely"}},
  8:  {efficiency:{min:0,max:100,lo:48,hi:70,desc:"KenPom 40–70 typical"},      form:{min:1,max:10,lo:4,hi:8,desc:"Hot or cold at season end"},        coaching:{min:1,max:10,lo:4,hi:8,desc:"Good range at this seed"},      regDiff:{min:1,max:10,lo:3,hi:7,desc:"Bubble survivor"}},
  9:  {efficiency:{min:0,max:100,lo:46,hi:68,desc:"Similar profile to 8-seeds"},form:{min:1,max:10,lo:4,hi:8,desc:"Nearly matched with 8"},           coaching:{min:1,max:10,lo:4,hi:8,desc:"Coin flip vs 8 on coaching"},  regDiff:{min:1,max:10,lo:3,hi:7,desc:"Close bubble call"}},
  10: {efficiency:{min:0,max:100,lo:42,hi:66,desc:"KenPom 50–80 typical"},      form:{min:1,max:10,lo:4,hi:8,desc:"Can be peaking late"},              coaching:{min:1,max:10,lo:3,hi:8,desc:"High variance here"},           regDiff:{min:1,max:10,lo:3,hi:7,desc:"Strong conference run"}},
  11: {efficiency:{min:0,max:100,lo:38,hi:63,desc:"Often play-in survivors"},   form:{min:1,max:10,lo:5,hi:9,desc:"Hot team — had to win to get here"},coaching:{min:1,max:10,lo:3,hi:8,desc:"Scrappy coaching typical"},     regDiff:{min:1,max:10,lo:3,hi:7,desc:"Proved it in play-in"}},
  12: {efficiency:{min:0,max:100,lo:33,hi:60,desc:"High/mid major split"},      form:{min:1,max:10,lo:4,hi:8,desc:"Peak form or mediocre finish"},      coaching:{min:1,max:10,lo:3,hi:8,desc:"Some veteran mid-major coaches"},regDiff:{min:1,max:10,lo:2,hi:6,desc:"Easier conference"}},
  13: {efficiency:{min:0,max:100,lo:26,hi:55,desc:"Mid-major auto-bids"},       form:{min:1,max:10,lo:3,hi:7,desc:"Conference tournament champs"},      coaching:{min:1,max:10,lo:2,hi:7,desc:"First-timers to veterans"},    regDiff:{min:1,max:10,lo:2,hi:6,desc:"Easy conference road"}},
  14: {efficiency:{min:0,max:100,lo:20,hi:50,desc:"Small conference auto-bids"},form:{min:1,max:10,lo:3,hi:7,desc:"Hot at conf. tournament"},           coaching:{min:1,max:10,lo:2,hi:6,desc:"First dance coaches common"},  regDiff:{min:1,max:10,lo:1,hi:5,desc:"Small conference winner"}},
  15: {efficiency:{min:0,max:100,lo:14,hi:45,desc:"Deep mid-major auto-bids"},  form:{min:1,max:10,lo:2,hi:7,desc:"Conference hot streak"},              coaching:{min:1,max:10,lo:1,hi:6,desc:"Major upset potential range"}, regDiff:{min:1,max:10,lo:1,hi:4,desc:"Weakest conference path"}},
  16: {efficiency:{min:0,max:100,lo:8, hi:38,desc:"Weakest bids in field"},     form:{min:1,max:10,lo:2,hi:6,desc:"One win away from history"},          coaching:{min:1,max:10,lo:1,hi:5,desc:"True Cinderella potential"},  regDiff:{min:1,max:10,lo:1,hi:4,desc:"Weakest path in the draw"}},
};
function getBounds(seed, metric) {
  return (SEED_BOUNDS[seed]||{})[metric] || {min:0,max:100,lo:0,hi:100,desc:""};
}
